### ISSUE TITLE
Dragging between lists

### ISSUE THREAD

**Issue by hako-studio** [Jexordexan/vue-slicksort#103] opened 2019-11-13 12:07 UTC
This is a fantastic project and the ability to drag in a grid is a feature I've not found anywhere else. However, I was wondering if there was a way you could drag and drop between two lists?

I have two arrays and I want to be able to move items between them; is this possible?

Thanks!

**Comment by alandecastros** [comment] 2019-11-14 21:10
I wanna know this too. 

Regards

**Comment by mgesmundo** [comment] 2019-11-14 22:28
Me too.
All the best

**Comment by edison1105** [comment] 2019-11-19 02:32
Me too.
if it can copy one item from A to B is better.

Regards.

**Comment by andygithubchen** [comment] 2020-02-27 12:04
Me too.
All the best
Regards.

**Comment by P4Thi0ut** [comment] 2020-04-19 13:16
Relates to [this idea](https://github.com/Jexordexan/vue-slicksort/issues/2)

**Comment by Jexordexan** [comment] 2021-02-06 23:12
Duplicate of #2

**Closed by Jexordexan** 2021-02-06 23:12 UTC
